### ISSUE TITLE
Issues compiling StarPrint iOS SDK with Xcode 16

### ISSUE THREAD

**Issue by randeep-ot** [star-micronics/StarPRNT-SDK-iOS-Swift#28] opened 2024-07-11 10:03 UTC
## Description
Unable to compile StarPrint iOS SDK with Xcode 16 beta 3

Error: 
Type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int
while building module 'StarlO_Extension' imported from ...:
in file included from <module-includes>: 1:
in file included from .../StarlO_Extension.framework/Headers/StarlO_Extension.h:18:

## Your development environment
 - Xcode 16 beta 3
 - SDK version: StarPRNT_iOS_SDK_V5.18.0_20240624

## Expected behavior
Able to compile with SDK

**Comment by bandit-ibayashi** [comment] 2024-07-19 02:57
@randeep-ot Thank you for posting this issue.
But I cannot reproduce this issue with Xcode16 Beta 3. The build was successfully.

If you continue to experience this issue, could you please provide more detailed steps and your development environment?
Also, would you experience any of the reported issues with the latest version of Xcode 15?

FYI: My environment is below:
````
Xcode Version 16.0 beta 3 (16A5202i)

% sw_vers
ProductName: macOS
ProductVersion: 14.5
BuildVersion: 23F79

iPad Air (4th Gen.). iPadOS 17.5.1
Simulator iPhone SE 3rd Gen. 18.0
````

Thanks.

**Comment by randeep-ot** [comment] 2024-07-19 07:11
Thanks @bandit-ibayashi. Compiling with Xcode 15.4 works fine.
Attaching a sample project to replicate the issue. Its a new project created with Xcode 15.4. If you open with Xcode 16 and build, you should see the error

[PStaIO-compile-issue.zip](https://github.com/user-attachments/files/16303771/PStaIO-compile-issue.zip)

**Comment by bandit-ibayashi** [comment] 2024-07-19 08:26
@randeep-ot Thank you for your prompt reply. We will try to reproduce with this information.

**Comment by justinstorm** [comment] 2024-07-31 13:14
@bandit-ibayashi  any updates on this?  we are running into the same issue with being unable to build in Xcode 16.

**Comment by bandit-ibayashi** [comment] 2024-08-21 10:09
Sorry for my late reply. We are still investing this issue.

In Xcode 16 Beta 5, the project provided by @randeep-ot was still not able to build.
But our StarPRNT SDK was able to do both Swift and Objective-C version. So we are investigating the factors that cause this.

Thank you for your patience.

**Comment by Mordil** [comment] 2024-08-21 16:12
For the record, Apple has claimed on the developer forums that this is considered a bug in Xcode and they are investigating https://forums.developer.apple.com/forums/thread/759861?page=1#797390022

**Comment by justinstorm** [comment] 2024-08-21 18:47
I can confirm that Xcode 16 Beta 6 resolved the issue for us! @Mordil @bandit-ibayashi

**Comment by Mordil** [comment] 2024-08-23 17:22
I have also confirmed that Xcode 16 Beta 6 resolves this issue.

**Comment by bandit-ibayashi** [comment] 2024-08-26 06:56
@Mordil @justinstorm Thank you for sharing this information and your confirmation.
I have also confirmed this was fixed on its Beta 6.

**Closed** 2024-09-25 06:03 UTC
Labels: Status: resolved, Target: sample code
