### ISSUE TITLE
Printer Connection Failed!!![BUG]

### ISSUE THREAD

**Issue by WenzhaoTan-Chowbus** [star-micronics/StarPRNT-SDK-iOS-Swift#16] opened 2022-05-24 09:20 UTC
## Description
- Restaurants continue to see Star Printer disconnection issues from time to time.
- We have provided an interim protocol to our local team: restart the iPad, forget Wi-Fi SSID and reconnect, and reset the iPad network setting.
- We still don't know what it means by PortName: TCP:10.1.10.122 code: -1 message: Connection failed.
- We suspect that IPv6 might cause the issue. But the printer was still disconnected after disabling the router's IPv6.

## Your device where the bug occurs 
 - Device: 
    iPad pro 1 & iPad mini 2
 - OS:
    iOS 12+
 - SDK: 
    StarIO (Ver. 2.9.0)
    StarIO_Extension (Ver. 1.16.0)
 - Version
    V5.15.0

## Your printer
- Model Names:
    mC-Print3、TSP100
- Firmware Version:
   3.4~3.6
- Interface:
    Ethernet、USB

## Your development environment
Xcode 13.4

## To Reproduce
We can't determine what caused this error. And when such an error occurs, we must restart the iPad or reset the iPad network to connect to the printer normally.
This happens by accident and we can't reproduce it with a specific scene or demo.

**Comment by BhavinRgrubbrr** [comment] 2022-06-06 06:16
@WenzhaoTan-Chowbus  @bandit-ibayashi  I am facing the same issue. After taking out some receipts, printer is getting disconnected. While checking for printer status it shows: `GetParsedStatus: PortException`. or `Failed to open port`

**Comment by asa47** [comment] 2022-10-28 10:10
@WenzhaoTan-Chowbus @BhavinRgrubbrr We are also facing the same issue, were you able to find a solution from your side?

**Comment by Tatsuki-Yamamoto2731** [comment] 2023-03-10 01:54
@WenzhaoTan-Chowbus Maybe the printer IP address is changed regularly by DHCP. In order to avoid this issue, you need to set the static IP address to the printer.
Could you please confirm your printer's network setting by self-printing?

How to self-printing:
https://www.star-m.jp/products/s_print/mcprint3/manual/en/basicOperations/testPrint.htm

How to setting static IP address
https://www.star-m.jp/products/s_print/mcprint3/manual/en/settings/settingsLAN.htm

**Comment by Tatsuki-Yamamoto2731** [comment] 2023-06-20 01:56
@WenzhaoTan-Chowbus Does this error occur with USB, too? Or Ethernet only?

**Comment by WenzhaoTan-Chowbus** [comment] 2023-06-25 02:10
We only use Ethernet

**Comment by bandit-ibayashi** [comment] 2024-03-13 03:39
Apologies for the delay in response on this issue.
In order to isolate the cause of this Issue, I would like you to try the following when this issue occurs.

* When this issue occurs, please try to open a web browser and enter the IP address of the printer in the URL section.
   + If the printer's Web Configuration screen appears, the reason could be due to the application.
   + If the Web Configuration screen is also not displayed, this issue may be caused by the network or the terminal.

Thank you in advance.

**Comment by bandit-ibayashi** [comment] 2024-10-03 04:41
We are afraid this Issue is closed as there has been no movement for over 6 months. If you continue to have issues, please let us know.

**Closed by bandit-ibayashi** 2024-10-03 04:41 UTC
Labels: Status: question, Target: other
