### ISSUE TITLE
is this sdk work for M1 processer ?

### ISSUE THREAD

**Issue by ali4fun** [star-micronics/StarPRNT-SDK-iOS-Swift#11] opened 2021-12-25 09:15 UTC
i am running on M1 macbook processor. it failing to run.

**Comment by gare-bear** [comment] 2021-12-27 22:52
Yes, this can be built on M1 Macs. Please be more specific on what is failing.

**Comment by ali4fun** [comment] 2022-01-04 06:46
sorry for late update. 
this error i get 
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CIContext", referenced from:
      objc-class-ref in SMCloudServices(SMCSAllReceipts.o)
      objc-class-ref in StarIO_Extension(SCBPdf417.o)
      objc-class-ref in StarIO_Extension(SCBQrCode.o)
  "_OBJC_CLASS_$_CIFilter", referenced from:
      objc-class-ref in SMCloudServices(SMCSAllReceipts.o)
      objc-class-ref in StarIO_Extension(SCBPdf417.o)
      objc-class-ref in StarIO_Extension(SCBQrCode.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`
please guide me if you faced this issue or have any idea how to fix it.

**Comment by gare-bear** [comment] 2022-01-06 15:39
@ali4fun Sounds like you might be using an older version of StarIO_Extension. 
The latest release of StarIO & StarIO_Extension adds support for the iOS Simulators.
https://github.com/star-micronics/StarPRNT-SDK-iOS-Swift/releases/tag/V5.15.0

Make sure you're using the latest frameworks.

**Comment by ali4fun** [comment] 2022-01-08 06:14
@gare-bear  thanks for a replay. 
I try to use latest versions but still facing same issue. 
these version I am using.
`Installing StarIO (2.9.0)
Installing StarIO_Extension (1.16.0) `
thank you

**Comment by ali4fun** [comment] 2022-01-27 07:33
@gare-bear  any update about this issue ?

**Comment by ali4fun** [comment] 2022-01-27 09:16
i tried on real device but still same issue. 
`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CIContext", referenced from:
      objc-class-ref in StarIO_Extension(SCBPdf417.o)
      objc-class-ref in StarIO_Extension(SCBQrCode.o)
  "_OBJC_CLASS_$_CIFilter", referenced from:
      objc-class-ref in StarIO_Extension(SCBPdf417.o)
      objc-class-ref in StarIO_Extension(SCBQrCode.o)
ld: symbol(s) not found for architecture arm64`

**Comment by gare-bear** [comment] 2022-01-27 14:20
@ali4fun I use an M1 Mac for daily development, so I know it works. 
if you can explain how to reproduce the issue, I can look into it further.

**Comment by ali4fun** [comment] 2022-01-30 04:29
sorry for LP. 
this is happened on startup when i try to install pods. 
`pod 'StarIO', '2.9.0'
pod 'StarIO_Extension','1.16.0'
pod 'StarIODeviceSetting','1.0.1'

**Comment by ali4fun** [comment] 2022-01-30 05:44
<img width="1409" alt="Screen Shot 2022-01-30 at 9 43 09 AM" src="https://user-images.githubusercontent.com/22047270/151688211-f6648148-6b85-44de-b9a9-ea87d3a28957.png">
@gare-bear  this is screen shoot. i hope you have fixed this issue.

**Comment by bandit-ibayashi** [comment] 2024-03-07 09:18
I'm arfaid it's been a long time.
I tried it on my M2 mac mini, and it worked without any errors like this.

``` console
% uname -m
arm64
% sw_vers
ProductName:		macOS
ProductVersion:		14.3.1
BuildVersion:		23D60
```

This error does not seem to be caused by the processor.
If this error continues to occur, **could you please build our sample SDK once?**
I think this will help isolate the cause.

**Comment by bandit-ibayashi** [comment] 2024-10-03 04:40
This issue is closed as there has been no movement for over 6 months. If you continue to have issues, please let us know.

**Closed by bandit-ibayashi** 2024-10-03 04:40 UTC
Labels: Status: help wanted, Target: other
