### ISSUE TITLE
[BUG] Inconsistency in printed receipts

### ISSUE THREAD

**Issue by arnolddrita** [star-micronics/StarPRNT-SDK-iOS-Swift#18] opened 2022-07-20 16:26 UTC
## Description
We have tested our code across a range of star printers and it all looks exactly the same. We are printing receipts by generating an in-memory bitmap of the whole receipt file and printing it using **appendBitmap** 

We've tested 3-4 different printers, on starGraphic and escPosMobile emulation modes (not sure if helpful), on Bluetooth, ethernet, wifi, and USB interfaces, and the printed image receipts look exactly the same (picture 1).

However, we're having issues with MCP31LB. The same iPad, connected to a TSP100, SM-T300 and an mC-Print3, printed the same receipt on all three. The first two, printed it exactly as picture 1, while the second consistently adds glitches to the image. Sometimes, just some sections of the image, appear centered. Other times, garbage is printed instead of the word (see the Restaurant word in the header). 

Not sure how to investigate this issue or what tests to perform to debug it. We are on the latest SDK version and latest iOS version.

## Your printer
- Model Names:
    *mC-Print3 MCP31LB*
    
## Screenshots
![correct_image](https://user-images.githubusercontent.com/18261031/180033949-0d6a5169-60df-4389-8245-88f7a22aaef5.jpg)

![bad_image](https://user-images.githubusercontent.com/18261031/180033996-9e8761c8-bdb9-4ba5-a91d-8e2ad61963b2.jpg)

**Comment by Tatsuki-Yamamoto2731** [comment] 2023-03-10 01:11
Unfortunately, I could not reproduce your problem.
OS: iPadOS 16.3
SDK: StarPRNT SDK V5.15.1

By the way, mC-Print3 supports "StarPRNT" emulation, not StarGraphic or ESC/POS Mobile.
So, you should specify StarPRNT emulation when you print from mC-Print3.
https://www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/ios_swift/en/api_starioext.html#emulation

Could you please confirm the emulation you use and try printing with the correct emulation?

**Comment by bandit-ibayashi** [comment] 2024-10-03 04:44
This issue is closed as there has been no movement for over an year. If you continue to have issues, please let us know.

**Closed by bandit-ibayashi** 2024-10-03 04:44 UTC
Labels: Status: help wanted
