### ISSUE TITLE
The "endCheckedBlock" is neccessary?

### ISSUE THREAD

**Issue by WenzhaoTan-Chowbus** [star-micronics/StarPRNT-SDK-iOS-Swift#6] opened 2021-04-30 06:42 UTC
# Version
StarPRNT  5.13.0
iOS 14.x

# Description
When I call the ```endCheckedBlock``` of port, sometimes it throws an error ```EndCheckedBlock : PortException```. But actually, the tickets have been printed out. 

# Question
Should we need to filter this error? Because it looks like the printer successfully prints the ticket.

**Comment by gare-bear** [comment] 2021-05-12 14:28
That will depend on the length of your receipts but 30s should be more than sufficient. 
Can you help me reproduce this issue?

**Comment by WenzhaoTan-Chowbus** [comment] 2021-05-14 01:49
Sorry, this issue is difficult to reproduce, we discovered it through our log system and user feedback.
And  `port.endCheckedBlock` this code return the error "EndCheckedBlock : PortException"

**Comment by gare-bear** [comment] 2021-08-30 22:43
@WenzhaoTan-Chowbus We're you able to fix the issue or find the cause?

If you can reproduce the issue more reliably, it would make debugging the issue much easier.
Also, it's really important that you use both begin & endCheckedBlock; you can't use one without the other.

**Comment by bandit-ibayashi** [comment] 2023-03-07 06:36
This issue will be closed as there has been no movement for a long period of time.
If you continue to experience similar issues, it would be appreciated if you could post another one.

**Closed by bandit-ibayashi** 2023-03-07 06:36 UTC
